spring.application.name=backend

# PostgreSQL Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/yigit
spring.datasource.username=yigit
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ve JPA Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect